<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <OutputType>Library</OutputType>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.14.0" />
      <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="4.14.0" />
      <PackageReference Include="System.Linq.Async" Version="6.0.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\C4ModelBuilder.Models\C4ModelBuilder.Models.csproj" />
    </ItemGroup>

    <ItemGroup>
      <InternalsVisibleTo Include="C4ModelBuilder.Analyzer.Tests" />
    </ItemGroup>

</Project>
